In [2]:
import pandas as pd

In [3]:
mov=pd.read_csv(r"C:\Users\hp\Desktop\Movies.csv")
mov

,Rank,Movie Title,Language,Domestic Revenue (₹ Cr),International Revenue (₹ Cr),Total Revenue (₹ Cr),Genre,Director,Release Date,Budget (₹ Cr),Main Cast,Runtime,Music Composer
0,1,Pushpa 2: The Rule,Telugu,"1,200",624,"1,824","Action, Thriller",Sukumar,15-Aug-24,400,"Allu Arjun, Rashmika Mandanna",170 min,Devi Sri Prasad
1,2,Kalki 2898 AD,Telugu,680,362,"1,042–1,200","Sci-Fi, Fantasy",Nag Ashwin,12-Jan-24,600,"Prabhas, Deepika Padukone, Amitabh Bachchan",180 min,M. M. Keeravani
2,3,Stree 2,Hindi,550,324,874.58,"Horror, Comedy",Amar Kaushik,31-Oct-24,80,"Rajkummar Rao, Shraddha Kapoor",145 min,Sachin-Jigar
3,4,The Greatest of All Time,Tamil,240,200,440–457.12,"Drama, Biography",Sudha Kongara,17-Nov-24,100,"Vijay Sethupathi, Keerthy Suresh",160 min,A.R. Rahman
4,5,Devara: Part 1,Telugu,315,88,403.83–521,"Action, Drama",Koratala Siva,25-Dec-24,250,"Jr NTR, Saif Ali Khan",165 min,Anirudh Ravichander
5,6,Bhool Bhulaiyaa 3,Hindi,358,65,423.85,"Horror, Comedy",Anees Bazmee,14-Mar-24,150,"Kartik Aaryan, Kiara Advani",155 min,Pritam
6,7,Singham Again,Hindi,310,79,389.64,"Action, Crime",Rohit Shetty,15-Aug-24,200,"Ajay Devgn, Kareena Kapoor",145 min,Devi Sri Prasad
7,8,Fighter,Hindi,270,74,344.46,"Action, Drama",Siddharth Anand,26-Jan-24,250,"Hrithik Roshan, Deepika Padukone",160 min,"Lijo George, DJ Chetas"
8,9,Shaitaan,Hindi,160,51,211.06,Thriller,Bejoy Nambiar,08-Nov-24,60,"Farhan Akhtar, Kriti Kharbanda",135 min,Shankar Ehsaan Loy
9,10,Crew,Hindi,123,34,157.08,"Comedy, Drama",Rajesh Krishnan,05-Apr-24,50,"Karisma Kapoor, Anil Kapoor",140 min,Vishal-Shekhar
10,11,Teri Baaton Mein Aisa Uljha Jiya,Hindi,120,13,133.64,"Romantic, Drama",Laxman Utekar,20-Sep-24,40,"Vicky Kaushal, Katrina Kaif",150 min,A.R. Rahman
11,12,Munjya,Hindi,115,17,132.13,Drama,Nitesh Tiwari,22-Nov-24,50,"Pankaj Tripathi, Shubham Pandey",130 min,Amit Trivedi
12,13,Bad Newz,Hindi,92,23,115.74,Thriller,Vikramaditya Motwane,12-Jul-24,70,"Ayushmann Khurrana, Tabu",160 min,Ankit Tiwari
13,14,Article 370,Hindi,85,25,110.57,"Drama, Politics",Anubhav Sinha,26-Jan-24,90,"Manoj Bajpayee, Richa Chadha",155 min,Amit Trivedi
14,15,Vettaiyan,Tamil,123,20,143.243,"Action, Drama",Lokesh Kanagaraj,18-Oct-24,150,"Vijay, Samantha Ruth Prabhu",165 min,Anirudh Ravichander

In [4]:
mov.head()

,Rank,Movie Title,Language,Domestic Revenue (₹ Cr),International Revenue (₹ Cr),Total Revenue (₹ Cr),Genre,Director,Release Date,Budget (₹ Cr),Main Cast,Runtime,Music Composer
0,1,Pushpa 2: The Rule,Telugu,"1,200",624,"1,824","Action, Thriller",Sukumar,15-Aug-24,400,"Allu Arjun, Rashmika Mandanna",170 min,Devi Sri Prasad
1,2,Kalki 2898 AD,Telugu,680,362,"1,042–1,200","Sci-Fi, Fantasy",Nag Ashwin,12-Jan-24,600,"Prabhas, Deepika Padukone, Amitabh Bachchan",180 min,M. M. Keeravani
2,3,Stree 2,Hindi,550,324,874.58,"Horror, Comedy",Amar Kaushik,31-Oct-24,80,"Rajkummar Rao, Shraddha Kapoor",145 min,Sachin-Jigar
3,4,The Greatest of All Time,Tamil,240,200,440–457.12,"Drama, Biography",Sudha Kongara,17-Nov-24,100,"Vijay Sethupathi, Keerthy Suresh",160 min,A.R. Rahman
4,5,Devara: Part 1,Telugu,315,88,403.83–521,"Action, Drama",Koratala Siva,25-Dec-24,250,"Jr NTR, Saif Ali Khan",165 min,Anirudh Ravichander

In [5]:
mov.sample(3)

,Rank,Movie Title,Language,Domestic Revenue (₹ Cr),International Revenue (₹ Cr),Total Revenue (₹ Cr),Genre,Director,Release Date,Budget (₹ Cr),Main Cast,Runtime,Music Composer
10,11,Teri Baaton Mein Aisa Uljha Jiya,Hindi,120,13,133.64,"Romantic, Drama",Laxman Utekar,20-Sep-24,40,"Vicky Kaushal, Katrina Kaif",150 min,A.R. Rahman
6,7,Singham Again,Hindi,310,79,389.64,"Action, Crime",Rohit Shetty,15-Aug-24,200,"Ajay Devgn, Kareena Kapoor",145 min,Devi Sri Prasad
12,13,Bad Newz,Hindi,92,23,115.74,Thriller,Vikramaditya Motwane,12-Jul-24,70,"Ayushmann Khurrana, Tabu",160 min,Ankit Tiwari

In [6]:
mov.shape

(15, 13)

In [7]:
mov['Movie Title']

0                   Pushpa 2: The Rule
1                        Kalki 2898 AD
2                              Stree 2
3             The Greatest of All Time
4                       Devara: Part 1
5                    Bhool Bhulaiyaa 3
6                        Singham Again
7                              Fighter
8                             Shaitaan
9                                 Crew
10    Teri Baaton Mein Aisa Uljha Jiya
11                              Munjya
12                            Bad Newz
13                         Article 370
14                           Vettaiyan
Name: Movie Title, dtype: object

In [8]:
mov['Budget (₹ Cr)'].max()

600

In [9]:
mov.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Rank                          15 non-null     int64
 1   Movie Title                   15 non-null     object
 2   Language                      15 non-null     object
 3   Domestic Revenue (₹ Cr)       15 non-null     object
 4   International Revenue (₹ Cr)  15 non-null     int64
 5   Total Revenue (₹ Cr)          15 non-null     object
 6   Genre                         15 non-null     object
 7   Director                      15 non-null     object
 8   Release Date                  15 non-null     object
 9   Budget (₹ Cr)                 15 non-null     int64
 10  Main Cast                     15 non-null     object
 11  Runtime                       15 non-null     object
 12  Music Composer                15 non-null     object
dtypes: int64(3), object(10)
memory usage: 1.7+ KB

In [10]:
mov.describe()

            Rank  International Revenue (₹ Cr)  Budget (₹ Cr)
count  15.000000                     15.000000      15.000000
mean    8.000000                    133.266667     169.333333
std     4.472136                    174.938955     155.722586
min     1.000000                     13.000000      40.000000
25%     4.500000                     24.000000      65.000000
50%     8.000000                     65.000000     100.000000
75%    11.500000                    144.000000     225.000000
max    15.000000                    624.000000     600.000000

In [11]:
mov['Budget (₹ Cr)'].max()

600

In [12]:
mov['Budget (₹ Cr)'].min()

40

In [13]:
mov['International Revenue (₹ Cr)'].max()

624

In [14]:
mov['International Revenue (₹ Cr)'].min()

13

In [15]:
mov[mov.Runtime=='160 min']

,Rank,Movie Title,Language,Domestic Revenue (₹ Cr),International Revenue (₹ Cr),Total Revenue (₹ Cr),Genre,Director,Release Date,Budget (₹ Cr),Main Cast,Runtime,Music Composer
3,4,The Greatest of All Time,Tamil,240,200,440–457.12,"Drama, Biography",Sudha Kongara,17-Nov-24,100,"Vijay Sethupathi, Keerthy Suresh",160 min,A.R. Rahman
7,8,Fighter,Hindi,270,74,344.46,"Action, Drama",Siddharth Anand,26-Jan-24,250,"Hrithik Roshan, Deepika Padukone",160 min,"Lijo George, DJ Chetas"
12,13,Bad Newz,Hindi,92,23,115.74,Thriller,Vikramaditya Motwane,12-Jul-24,70,"Ayushmann Khurrana, Tabu",160 min,Ankit Tiwari

In [16]:
mov[mov.Genre=='Action, Drama']

,Rank,Movie Title,Language,Domestic Revenue (₹ Cr),International Revenue (₹ Cr),Total Revenue (₹ Cr),Genre,Director,Release Date,Budget (₹ Cr),Main Cast,Runtime,Music Composer
4,5,Devara: Part 1,Telugu,315,88,403.83–521,"Action, Drama",Koratala Siva,25-Dec-24,250,"Jr NTR, Saif Ali Khan",165 min,Anirudh Ravichander
7,8,Fighter,Hindi,270,74,344.46,"Action, Drama",Siddharth Anand,26-Jan-24,250,"Hrithik Roshan, Deepika Padukone",160 min,"Lijo George, DJ Chetas"
14,15,Vettaiyan,Tamil,123,20,143.243,"Action, Drama",Lokesh Kanagaraj,18-Oct-24,150,"Vijay, Samantha Ruth Prabhu",165 min,Anirudh Ravichander

In [17]:
mov.drop(['Genre','Rank'],axis=1)

,Movie Title,Language,Domestic Revenue (₹ Cr),International Revenue (₹ Cr),Total Revenue (₹ Cr),Director,Release Date,Budget (₹ Cr),Main Cast,Runtime,Music Composer
0,Pushpa 2: The Rule,Telugu,"1,200",624,"1,824",Sukumar,15-Aug-24,400,"Allu Arjun, Rashmika Mandanna",170 min,Devi Sri Prasad
1,Kalki 2898 AD,Telugu,680,362,"1,042–1,200",Nag Ashwin,12-Jan-24,600,"Prabhas, Deepika Padukone, Amitabh Bachchan",180 min,M. M. Keeravani
2,Stree 2,Hindi,550,324,874.58,Amar Kaushik,31-Oct-24,80,"Rajkummar Rao, Shraddha Kapoor",145 min,Sachin-Jigar
3,The Greatest of All Time,Tamil,240,200,440–457.12,Sudha Kongara,17-Nov-24,100,"Vijay Sethupathi, Keerthy Suresh",160 min,A.R. Rahman
4,Devara: Part 1,Telugu,315,88,403.83–521,Koratala Siva,25-Dec-24,250,"Jr NTR, Saif Ali Khan",165 min,Anirudh Ravichander
5,Bhool Bhulaiyaa 3,Hindi,358,65,423.85,Anees Bazmee,14-Mar-24,150,"Kartik Aaryan, Kiara Advani",155 min,Pritam
6,Singham Again,Hindi,310,79,389.64,Rohit Shetty,15-Aug-24,200,"Ajay Devgn, Kareena Kapoor",145 min,Devi Sri Prasad
7,Fighter,Hindi,270,74,344.46,Siddharth Anand,26-Jan-24,250,"Hrithik Roshan, Deepika Padukone",160 min,"Lijo George, DJ Chetas"
8,Shaitaan,Hindi,160,51,211.06,Bejoy Nambiar,08-Nov-24,60,"Farhan Akhtar, Kriti Kharbanda",135 min,Shankar Ehsaan Loy
9,Crew,Hindi,123,34,157.08,Rajesh Krishnan,05-Apr-24,50,"Karisma Kapoor, Anil Kapoor",140 min,Vishal-Shekhar
10,Teri Baaton Mein Aisa Uljha Jiya,Hindi,120,13,133.64,Laxman Utekar,20-Sep-24,40,"Vicky Kaushal, Katrina Kaif",150 min,A.R. Rahman
11,Munjya,Hindi,115,17,132.13,Nitesh Tiwari,22-Nov-24,50,"Pankaj Tripathi, Shubham Pandey",130 min,Amit Trivedi
12,Bad Newz,Hindi,92,23,115.74,Vikramaditya Motwane,12-Jul-24,70,"Ayushmann Khurrana, Tabu",160 min,Ankit Tiwari
13,Article 370,Hindi,85,25,110.57,Anubhav Sinha,26-Jan-24,90,"Manoj Bajpayee, Richa Chadha",155 min,Amit Trivedi
14,Vettaiyan,Tamil,123,20,143.243,Lokesh Kanagaraj,18-Oct-24,150,"Vijay, Samantha Ruth Prabhu",165 min,Anirudh Ravichander

In [18]:
mov[['Rank','Movie Title','Total Revenue (₹ Cr)']]

    Rank                       Movie Title Total Revenue (₹ Cr)
0      1                Pushpa 2: The Rule                1,824
1      2                     Kalki 2898 AD          1,042–1,200
2      3                           Stree 2               874.58
3      4          The Greatest of All Time           440–457.12
4      5                    Devara: Part 1           403.83–521
5      6                 Bhool Bhulaiyaa 3               423.85
6      7                     Singham Again               389.64
7      8                           Fighter               344.46
8      9                          Shaitaan               211.06
9     10                              Crew               157.08
10    11  Teri Baaton Mein Aisa Uljha Jiya               133.64
11    12                            Munjya               132.13
12    13                          Bad Newz               115.74
13    14                       Article 370               110.57
14    15                         Vettaiyan              143.243

In [19]:
mov.sort_values('International Revenue (₹ Cr)')

,Rank,Movie Title,Language,Domestic Revenue (₹ Cr),International Revenue (₹ Cr),Total Revenue (₹ Cr),Genre,Director,Release Date,Budget (₹ Cr),Main Cast,Runtime,Music Composer
10,11,Teri Baaton Mein Aisa Uljha Jiya,Hindi,120,13,133.64,"Romantic, Drama",Laxman Utekar,20-Sep-24,40,"Vicky Kaushal, Katrina Kaif",150 min,A.R. Rahman
11,12,Munjya,Hindi,115,17,132.13,Drama,Nitesh Tiwari,22-Nov-24,50,"Pankaj Tripathi, Shubham Pandey",130 min,Amit Trivedi
14,15,Vettaiyan,Tamil,123,20,143.243,"Action, Drama",Lokesh Kanagaraj,18-Oct-24,150,"Vijay, Samantha Ruth Prabhu",165 min,Anirudh Ravichander
12,13,Bad Newz,Hindi,92,23,115.74,Thriller,Vikramaditya Motwane,12-Jul-24,70,"Ayushmann Khurrana, Tabu",160 min,Ankit Tiwari
13,14,Article 370,Hindi,85,25,110.57,"Drama, Politics",Anubhav Sinha,26-Jan-24,90,"Manoj Bajpayee, Richa Chadha",155 min,Amit Trivedi
9,10,Crew,Hindi,123,34,157.08,"Comedy, Drama",Rajesh Krishnan,05-Apr-24,50,"Karisma Kapoor, Anil Kapoor",140 min,Vishal-Shekhar
8,9,Shaitaan,Hindi,160,51,211.06,Thriller,Bejoy Nambiar,08-Nov-24,60,"Farhan Akhtar, Kriti Kharbanda",135 min,Shankar Ehsaan Loy
5,6,Bhool Bhulaiyaa 3,Hindi,358,65,423.85,"Horror, Comedy",Anees Bazmee,14-Mar-24,150,"Kartik Aaryan, Kiara Advani",155 min,Pritam
7,8,Fighter,Hindi,270,74,344.46,"Action, Drama",Siddharth Anand,26-Jan-24,250,"Hrithik Roshan, Deepika Padukone",160 min,"Lijo George, DJ Chetas"
6,7,Singham Again,Hindi,310,79,389.64,"Action, Crime",Rohit Shetty,15-Aug-24,200,"Ajay Devgn, Kareena Kapoor",145 min,Devi Sri Prasad
4,5,Devara: Part 1,Telugu,315,88,403.83–521,"Action, Drama",Koratala Siva,25-Dec-24,250,"Jr NTR, Saif Ali Khan",165 min,Anirudh Ravichander
3,4,The Greatest of All Time,Tamil,240,200,440–457.12,"Drama, Biography",Sudha Kongara,17-Nov-24,100,"Vijay Sethupathi, Keerthy Suresh",160 min,A.R. Rahman
2,3,Stree 2,Hindi,550,324,874.58,"Horror, Comedy",Amar Kaushik,31-Oct-24,80,"Rajkummar Rao, Shraddha Kapoor",145 min,Sachin-Jigar
1,2,Kalki 2898 AD,Telugu,680,362,"1,042–1,200","Sci-Fi, Fantasy",Nag Ashwin,12-Jan-24,600,"Prabhas, Deepika Padukone, Amitabh Bachchan",180 min,M. M. Keeravani
0,1,Pushpa 2: The Rule,Telugu,"1,200",624,"1,824","Action, Thriller",Sukumar,15-Aug-24,400,"Allu Arjun, Rashmika Mandanna",170 min,Devi Sri Prasad

In [20]:
mov['Total Revenue (₹ Cr)'].value_counts

<bound method IndexOpsMixin.value_counts of 0           1,824
1     1,042–1,200
2          874.58
3      440–457.12
4      403.83–521
5          423.85
6          389.64
7          344.46
8          211.06
9          157.08
10         133.64
11         132.13
12         115.74
13         110.57
14        143.243
Name: Total Revenue (₹ Cr), dtype: object>